# Generated by Django 4.2.10 on 2024-02-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dino',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dino',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
