# Generated by Django 4.2.10 on 2024-03-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_vaccines_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='date',
            field=models.DateField(verbose_name='Vaccine Administration Date'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='shot',
            field=models.CharField(choices=[('F', 'Flu'), ('P', 'Parvovirus'), ('R', 'Rotavirus'), ('T', 'Tetanus'), ('M', 'Measles')], default='F', max_length=1, verbose_name='Vaccine Administered'),
        ),
    ]
