# Generated by Django 4.2.10 on 2024-03-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_milestone_alter_vaccine_options_alter_vaccine_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
