# Generated by Django 4.2.10 on 2024-03-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_milestone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dino',
            name='milestones',
            field=models.ManyToManyField(to='main_app.milestone'),
        ),
    ]
